name: My Starter Workflow

on:
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      node: 14
    strategy:
      matrix:
        nodeversion: [14, 16, 18, 20]

  # This is a new job that should satisfy the step checker
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy to your project.
